import libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
tf.__version__

'2.6.0'

import data set

In [ ]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X)
print(Y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


**encoding the categorical** **data**

label encoder on gender

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


one hot incoding on geography

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


splitting the data into training and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=0)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [ ]:
print(Y_train)

[0 0 0 ... 0 0 1]


In [ ]:
print(Y_test)

[0 1 0 ... 0 0 0]


apply featurescaling on the training set

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [ ]:
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


**Building the ANN**

initializing the ANN

In [ ]:
## inisilizing the ann as sequence of layers
## fully connected layers
## ann is the object of Sequential  class
ann = tf.keras.models.Sequential()



adding the input layer and first hidden layer

In [ ]:
## this layer is object of  Dense class
## we use add methods  from the Sequential class
## used layer modules
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))


adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation="relu"))

adding the outer layer

In [ ]:
## activation is sigmoid becoz we are predicted only 0 or 1 means binary outcome so only need 1 nueron
## if not predicting binary classification than activation should be "softmax" 
ann.add(tf.keras.layers.Dense(units = 1, activation="sigmoid"))

**training the ANN**

compiling the ANN

In [ ]:
# when you have to predict the binary outcome tha always use loss - "binary_crossentropy"
# when there is non binary classification than use loss - categorical_crossentropy

ann.compile(optimizer= "adam", loss= "binary_crossentropy", metrics= ['accuracy'])

training the ANN on the training set

In [ ]:
ann.fit(X_train, Y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5216 - accuracy: 0.7958
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4666 - accuracy: 0.7991
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4468 - accuracy: 0.8058
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4374 - accuracy: 0.8061
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4312 - accuracy: 0.8087
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4262 - accuracy: 0.8106
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4221 - accuracy: 0.8112
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4182 - accuracy: 0.8129
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4145 - accuracy: 0.8123
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4113 - accura

**making the prediction and evaluating the model**

predicting the result of a single observation (this customer will leave the bank or not)

In [ ]:
##ann trained on feature scaling so predict method also use smae scale 

print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[0.02808473]]
[[False]]


predicting the test result

In [ ]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred>0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


making the confusing  matrix

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1501   94]
 [ 195  210]]


0.8555